version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: degg
    main: ./cmd/degg
    binary: degg
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/caian-org/degg/cmd/degg/cli.ProgramVersion={{ .Version }}
      - -X github.com/caian-org/degg/cmd/degg/cli.ProgramCommitSHA={{ .ShortCommit }}
      - -X github.com/caian-org/degg/cmd/degg/cli.ProgramBuildTime={{ .Date }}

archives:
  - ids:
      - degg
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
